export const mart = [
    {
        id: 1,
        name: 'Eggs',
        price: '3',
        image: '',
    },
    {
        id: 2, 
        name: 'apples',
        price: 2,
        image: '',
    },
    {
        id: 3, 
        name: 'Tomatoes',
        price: 4,
        image: '',
    },
    {
        id: 4, 
        name: 'Cooking oil',
        price: 2.23,
        image: '',
    },
    {
        id: 5, 
        name: 'Salt',
        price: 3.12,
        image: '',
    },
    {
        id: 6, 
        name: 'Carrots',
        price: 5,
        image: '',
    },
    {
        id: 7, 
        name: 'Onions',
        price: 3.21,
        image: '',
    },
    {
        id: 8, 
        name: 'Flour',
        price: 4.20,
        image: '',
    },
    {
        id: 9, 
        name: 'Vinegar',
        price: 2.44,
        image: '',
    },
    {
        id: 10, 
        name: 'Apples',
        price: 2,
        image: '',
    },
    {
        id: 11, 
        name: 'Bananas',
        price: 2,
        image: '',
    },
    {
        id: 12, 
        name: 'Strawberries',
        price: 5.50,
        image: '',
    },
    {
        id: 13, 
        name: 'Grapes',
        price: 4.95,
        image: '',
    },
    {
        id: 14, 
        name: 'Mangoes',
        price: 3,
        image: '',
    },
    {
        id: 15, 
        name: 'Bread',
        price: 3.23,
        image: '',
    },
    {
        id: 16, 
        name: 'Snickers',
        price: 8,
        image: '',
    },
    {
        id: 17, 
        name: 'Kit Kat',
        price: 9.20,
        image: '',
    },
    {
        id: 18, 
        name: 'Cabbages',
        price: 3.20,
        image: '',
    },
    {
        id: 19, 
        name: 'Potatoes',
        price: 4.10,
        image: '',
    },
    {
        id: 20, 
        name: 'Cucumber',
        price: 2.45,
        image: '',
    },
]