export const martProducts = [
    {
        id: 1,
        name: 'Eggs',
        price: '3',
        image: 'https://png.pngtree.com/png-clipart/20230131/ourmid/pngtree-egg-fresh-egg-food-png-image_6196297.png',
    },
    {
        id: 2, 
        name: 'Apples',
        price: 2,
        image: 'https://freepngimg.com/save/9556-apple-fruit-png/736x445',
    },
    {
        id: 3, 
        name: 'Tomatoes',
        price: 4,
        image: 'https://www.sunsetgrown.com/wp-content/uploads/elementor/thumbs/tomato-hero4-oy08zalhwrt2d2tith502empq61clwj59w4pxy9ef8.png',
    },
    {
        id: 4, 
        name: 'Avocados',
        price: 2.23,
        image: 'https://www.pngmart.com/files/5/Avocado-PNG-HD.png',
    },
    {
        id: 5, 
        name: 'Salt',
        price: 3.12,
        image: 'https://www.pngplay.com/wp-content/uploads/2/Salt-PNG-Free-File-Download.png',
    },
    {
        id: 6, 
        name: 'Carrots',
        price: 5,
        image: 'https://purepng.com/public/uploads/thumbnail/purepng.com-carrotscarrotvegetablesfreshdeliciousefoodhealthycarrots-481521740717y8bwq.png',
    },
    {
        id: 7, 
        name: 'Onions',
        price: 3.21,
        image: 'https://www.pngall.com/wp-content/uploads/2016/03/Onion-PNG-Picture.png',
    },
    {
        id: 8, 
        name: 'Flour',
        price: 4.20,
        image: 'https://goodmanfielder.com/assets/PNG-Range-shots-370-x-300/Flame-Plain-Flour__FillWzYwMCw2MDBd.png',
    },
    {
        id: 9, 
        name: 'Vinegar',
        price: 2.44,
        image: 'https://www.musselmans.com/wp-content/uploads/DIST-128oz-750x563-1-750x563.png',
    },
    {
        id: 10, 
        name: 'Lettuce',
        price: 2,
        image: 'https://freepngimg.com/save/147712-lettuce-organic-butterhead-download-free-image/940x758',
    },
    {
        id: 11, 
        name: 'Bananas',
        price: 2,
        image: 'https://www.seekpng.com/png/full/34-341853_banana-png-image-with-transparent-background-1-pound.png',
    },
    {
        id: 12, 
        name: 'Strawberries',
        price: 5.50,
        image: 'https://freepngdownload.com/image/thumb/strawberry-png-free-download-15.png',
    },
    {
        id: 13, 
        name: 'Grapes',
        price: 4.95,
        image: 'https://www.pngmart.com/files/1/Green-Grapes-PNG.png',
    },
    {
        id: 14, 
        name: 'Mangoes',
        price: 3,
        image: 'https://www.pngkey.com/png/full/364-3643518_mango.png',
    },
    {
        id: 15, 
        name: 'Bread',
        price: 3.23,
        image: 'https://www.pngkey.com/png/full/15-159855_wheat-bread-png.png',
    },
    {
        id: 16, 
        name: 'Snickers',
        price: 8,
        image: 'https://www.pngmart.com/files/22/Snickers-PNG-Isolated-HD.png',
    },
    {
        id: 17, 
        name: 'Kit Kat',
        price: 9.20,
        image: 'https://www.lifepng.com/wp-content/uploads/2021/01/Mini-KitKat-Bars-png-hd.png',
    },
    {
        id: 18, 
        name: 'Cabbages',
        price: 3.20,
        image: 'https://www.pngall.com/wp-content/uploads/2016/05/Cabbage.png',
    },
    {
        id: 19, 
        name: 'Skittles',
        price: 4.10,
        image: 'https://ptlone.com/product/image/medium/c2050_0.png',
    },
    {
        id: 20, 
        name: 'Lemons',
        price: 2.45,
        image: 'https://www.freepnglogos.com/uploads/lemon-png/lemon-juice-sampar-drinking-water-19.png',
    },
]